spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb
    username: appuser
    password: appuser

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/html/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true